default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  # adapter: postgresql
  # encoding: unicode
  # database: summits-db
  # username: gkrathwohl@summit-postgresql
  # password: volar421!
  # host: summit-postgresql.postgres.database.azure.com
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: summits-db
#   username: gkrathwohl@summit-postgresql
#   password: volar421!
#   host: summit-postgresql.postgres.database.azure.com

production:
  adapter: postgresql
  host: 127.0.0.1
  database: summits_production
  username: deploy
  password:
  encoding: unicode
  pool: 5